language: ruby
sudo: false
before_install: gem install bundler

bundler_args: --without development doc

rvm:
  - jruby-9.1.5.0
  - 2.0
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.1

matrix:
  fast_finish: true

branches:
  only:
    - master
