language: ruby
sudo: false
before_install: gem install bundler

bundler_args: --without development doc

script: bundle exec rake ci

rvm:
  - jruby
  - 2.4
  - 2.5
  - 2.6

matrix:
  fast_finish: true
  include:
  # Only run RuboCop on the latest Ruby
  - env: SUITE="rubocop"
    rvm: 2.6

branches:
  only:
    - master
